// Generated by CoffeeScript 1.4.0
(function() {
  var TwitterSpeechSearch,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  TwitterSpeechSearch = (function() {

    function TwitterSpeechSearch(input, tweetsWrap) {
      this.input = input;
      this.tweetsWrap = tweetsWrap;
      this.validate = __bind(this.validate, this);

      this.search = __bind(this.search, this);

      this.input.on('webkitspeechchange', this.search);
    }

    TwitterSpeechSearch.prototype.search = function(e) {
      var query;
      query = this.input.val();
      if (!query) {
        return;
      }
      return $.getJSON("http://search.twitter.com/search.json?callback=?&q=" + (encodeURI(query)), this.validate);
    };

    TwitterSpeechSearch.prototype.validate = function(result) {
      if (result.results.length < 1) {
        alert("Nothing matched your query '" + (this.input.val()) + "'. Try again.");
        return;
      }
      console.log(result.results[0]);
      this.tweets = $.map(result.results, function(tweet) {
        return {
          id: tweet.id_str,
          text: tweet.text,
          avatar: tweet.profile_image_url,
          user: tweet.from_user,
          img: tweet.profile_image_url,
          timestamp: tweet.created_at
        };
      });
      return this.renderTweets();
    };

    TwitterSpeechSearch.prototype.renderTweets = function() {
      var html, tweet, _i, _len, _ref;
      html = '<ul class="tweets">';
      _ref = this.tweets;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        tweet = _ref[_i];
        html += "				<li class='tweet'>					<section class='content'>						<div class='user'>							<div class='avatar'>								<img src='" + tweet.img + "' width='35' height='35'>							</div>						</div>						<div class='drop-shadow lifted'>							" + tweet.text + "						</div>					</section>					<footer>						<a href='http://twitter.com/" + tweet.user + "/status/" + tweet.id + "' title='View tweet on Twitter.com' target='_blank'>@" + tweet.user + "</a>						<p class='timestamp'>" + (this.formatTimestamp(tweet.timestamp)) + "</p>					</footer>				</li>			";
      }
      html += '</ul>';
      return this.tweetsWrap.empty().append($(html));
    };

    TwitterSpeechSearch.prototype.formatTimestamp = function(timestamp) {
      return timestamp.replace(/(\s[0-9][0-9]:.+$)/g, '');
    };

    return TwitterSpeechSearch;

  })();

  new TwitterSpeechSearch($('#talktome'), $('#tweets'));

}).call(this);
